-- CREATE SCHEMA FOR MIGRATION
CREATE SCHEMA IF NOT EXISTS fpvlovers_app;

-- ENABLE UUID EXTENSION (IF AVAILABLE)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- CREATE SCHEMA MIGRATIONS TABLE
CREATE TABLE IF NOT EXISTS fpvlovers_app.schema_migrations (
  version VARCHAR(50) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  checksum VARCHAR(64) NOT NULL,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
