import type { ContentBrief, ContentCategory } from './content-types';

const coreContentPlan = [
  {
    slug: 'fpv-beginner-setup-guide',
    title: 'FPV Beginner Setup Guide: The Easiest Way to Get Flying',
    category: 'Flight Guides',
    tier: 'pillar',
    audience: 'beginner',
    searchIntent: 'informational',
    primaryKeyword: 'FPV beginner setup guide',
    secondaryKeywords: [
      'how to start FPV',
      'FPV setup for beginners',
      'first FPV drone checklist',
    ],
    seoTitle: 'FPV Beginner Setup Guide for New Pilots',
    metaDescription:
      'Learn the simplest FPV starter setup, from the radio and goggles to the drone, batteries, and first flight checklist.',
    summary:
      'A beginner-first walkthrough of the FPV starter stack, the order to buy gear, and the safest way to get ready for a first flight.',
    whyThisMatters:
      'This is the highest-intent starting point for new pilots and creates a strong internal path into build, component, and troubleshooting content.',
    outline: [
      'What FPV is and how the gear works together',
      'The best first purchase order for new pilots',
      'Analog versus digital at a beginner level',
      'A simple first-flight prep checklist',
      'What to learn before buying a second drone',
    ],
    estimatedWordCount: 2200,
  },
  {
    slug: 'fpv-troubleshooting-guide',
    title: 'FPV Troubleshooting Guide: Fix the Most Common Problems Fast',
    category: 'Troubleshooting',
    tier: 'pillar',
    audience: 'beginner',
    searchIntent: 'diagnostic',
    primaryKeyword: 'FPV troubleshooting guide',
    secondaryKeywords: [
      'FPV drone problems',
      'no video FPV fix',
      'FPV drone will not arm',
    ],
    seoTitle: 'FPV Troubleshooting Guide for Common Drone Problems',
    metaDescription:
      'Diagnose no-video, no-arm, binding, and startup issues with a simple FPV troubleshooting flow built for beginners.',
    summary:
      'A practical troubleshooting hub for the most common FPV issues, organized by symptom so new pilots can find a fix quickly.',
    whyThisMatters:
      'Troubleshooting content captures strong search intent and keeps beginner pilots from abandoning the hobby after a first problem.',
    outline: [
      'Start with power, wiring, and basic safety checks',
      'How to isolate radio, video, and flight-controller issues',
      'No video, no arm, and failsafe troubleshooting',
      'When the problem is a setup mistake versus a broken part',
      'A repeatable checklist for bench testing and repair',
    ],
    estimatedWordCount: 2400,
  },
  {
    slug: 'fpv-components-wiring-guide',
    title: 'FPV Components and Wiring Guide: What Each Part Does',
    category: 'Build Guides',
    tier: 'pillar',
    audience: 'beginner-to-intermediate',
    searchIntent: 'informational',
    primaryKeyword: 'FPV components and wiring guide',
    secondaryKeywords: [
      'FPV drone parts explained',
      'how FPV drone wiring works',
      'motor ESC flight controller basics',
    ],
    seoTitle: 'FPV Components and Wiring Guide for Beginners',
    metaDescription:
      'Understand the main FPV drone parts, how they connect, and the wiring logic behind a clean beginner build.',
    summary:
      'A beginner-friendly map of every core FPV component, what it does, and how the signal and power paths fit together.',
    whyThisMatters:
      'This pillar supports future build articles and helps readers understand upgrades, repairs, and compatibility decisions.',
    outline: [
      'The job of each core FPV component',
      'Power flow, signal flow, and basic wiring logic',
      'Motor, ESC, FC, camera, VTX, antenna, and receiver roles',
      'Common compatibility mistakes to avoid',
      'How to read a simple wiring diagram',
    ],
    estimatedWordCount: 2300,
  },
  {
    slug: 'how-to-choose-your-first-fpv-radio',
    title: 'How to Choose Your First FPV Radio Without Buying Twice',
    category: 'Components',
    tier: 'support',
    audience: 'beginner',
    searchIntent: 'commercial',
    primaryKeyword: 'best FPV radio for beginners',
    secondaryKeywords: [
      'first FPV transmitter',
      'radio protocol for FPV beginners',
      'ELRS or Crossfire beginner',
    ],
    seoTitle: 'How to Choose Your First FPV Radio',
    metaDescription:
      'Compare beginner FPV radios, protocol support, ergonomics, and upgrade path so you can buy once and fly longer.',
    summary:
      'A practical buying guide that helps new pilots choose a radio based on protocol support, ergonomics, and future upgrade path.',
    whyThisMatters:
      'Radio choice shapes the whole pilot experience and is often the first meaningful hardware purchase after goggles.',
    outline: [
      'What a radio link does in FPV',
      'ELRS, Crossfire, and legacy options at a beginner level',
      'Size, gimbals, switches, and ergonomics',
      'What to look for if you plan to keep upgrading',
      'Recommended decision path by budget',
    ],
    estimatedWordCount: 1700,
  },
  {
    slug: 'fpv-goggles-buying-guide',
    title: 'FPV Goggles Buying Guide: Analog vs Digital for Beginners',
    category: 'News and Reviews',
    tier: 'support',
    audience: 'beginner',
    searchIntent: 'comparative',
    primaryKeyword: 'FPV goggles buying guide',
    secondaryKeywords: [
      'analog vs digital FPV goggles',
      'best FPV goggles for beginners',
      'FPV headset comparison',
    ],
    seoTitle: 'FPV Goggles Buying Guide for Beginners',
    metaDescription:
      'Compare FPV goggles by ecosystem, image quality, comfort, latency, and budget so beginner pilots can choose with confidence.',
    summary:
      'A comparison-led guide to the first goggle purchase, with a clear look at analog and digital tradeoffs for new pilots.',
    whyThisMatters:
      'Goggles are one of the biggest purchase decisions in FPV, and searchers want a clean comparison before they commit.',
    outline: [
      'How FPV goggles fit into the pilot setup',
      'Analog versus digital image quality and cost',
      'Comfort, fit, and receiver options',
      'Budget tiers and upgrade paths',
      'Which choice makes sense for first-time buyers',
    ],
    estimatedWordCount: 1800,
  },
  {
    slug: 'vtx-and-camera-setup-guide',
    title: 'VTX and Camera Setup Guide: Clean Video From the Start',
    category: 'Build Guides',
    tier: 'support',
    audience: 'beginner-to-intermediate',
    searchIntent: 'informational',
    primaryKeyword: 'VTX and camera setup guide',
    secondaryKeywords: [
      'FPV camera wiring',
      'VTX channel setup',
      'FPV video transmitter basics',
    ],
    seoTitle: 'VTX and Camera Setup Guide for FPV Drones',
    metaDescription:
      'Set up your FPV camera and VTX correctly with a simple wiring and configuration guide that prevents common video problems.',
    summary:
      'A focused guide to setting up the video system so beginners can get a clean image and avoid the usual channel and wiring mistakes.',
    whyThisMatters:
      'Video setup mistakes create some of the most frustrating beginner failures, including bad signal, black screens, and noisy footage.',
    outline: [
      'What the camera and VTX do',
      'Wiring basics and common pin mistakes',
      'Channel, band, and power setup',
      'How to test video before the first flight',
      'Avoiding overheating and interference issues',
    ],
    estimatedWordCount: 1600,
  },
  {
    slug: 'no-video-fpv-troubleshooting',
    title: 'No Video in FPV: A Beginner Troubleshooting Checklist',
    category: 'Troubleshooting',
    tier: 'support',
    audience: 'beginner',
    searchIntent: 'diagnostic',
    primaryKeyword: 'FPV no video fix',
    secondaryKeywords: [
      'FPV goggles show no signal',
      'black screen FPV drone',
      'video transmitter troubleshooting',
    ],
    seoTitle: 'No Video FPV Troubleshooting Checklist',
    metaDescription:
      'Use this step-by-step checklist to fix common FPV no-video problems in the camera, VTX, antenna, and goggle chain.',
    summary:
      'A symptom-based checklist for the most common FPV problem: the goggles power on, but no usable video appears.',
    whyThisMatters:
      'No-video issues are a common first-flight blocker and one of the most valuable beginner troubleshooting searches.',
    outline: [
      'Check power, antenna, and channel settings first',
      'Separate camera, VTX, and goggle failures',
      'What to inspect on the bench before re-arming',
      'Easy fixes for wiring and configuration problems',
      'When to replace a component',
    ],
    estimatedWordCount: 1500,
  },
  {
    slug: 'betaflight-pid-basics-for-beginners',
    title: 'Betaflight PID Basics for Beginners: Start With the Right Mental Model',
    category: 'Flight Guides',
    tier: 'support',
    audience: 'beginner-to-intermediate',
    searchIntent: 'informational',
    primaryKeyword: 'Betaflight PID basics',
    secondaryKeywords: [
      'Betaflight tuning for beginners',
      'what are PID values',
      'FPV flight controller tuning',
    ],
    seoTitle: 'Betaflight PID Basics for Beginners',
    metaDescription:
      'Learn the beginner-friendly meaning of PID tuning in Betaflight and how to approach small changes without breaking a good tune.',
    summary:
      'A simple explanation of PID tuning that helps new pilots understand what changes matter and what to leave alone.',
    whyThisMatters:
      'PID tuning is a frequent search path for pilots who want better handling, and beginner clarity here reduces fear and mistakes.',
    outline: [
      'What PID tuning actually changes',
      'Why a decent stock tune is enough at first',
      'How to think about drift, bounce, and oscillation',
      'Safe beginner adjustments and testing habits',
      'When tuning should stop and component checks should start',
    ],
    estimatedWordCount: 1700,
  },
  {
    slug: 'fpv-racing-beginner-guide',
    title: 'FPV Racing for Beginners: What to Practice First',
    category: 'Racing',
    tier: 'support',
    audience: 'beginner',
    searchIntent: 'informational',
    primaryKeyword: 'FPV racing for beginners',
    secondaryKeywords: [
      'how to start FPV racing',
      'FPV race practice drills',
      'beginner FPV race setup',
    ],
    seoTitle: 'FPV Racing for Beginners',
    metaDescription:
      'Start FPV racing with the right practice drills, race mindset, and basic setup choices that keep learning simple.',
    summary:
      'A beginner racing guide that focuses on practice structure, track awareness, and the simplest path into competition.',
    whyThisMatters:
      'Racing brings a distinct audience and helps broaden the site beyond setup content while still serving beginners.',
    outline: [
      'What makes racing different from freestyle or cinematic flying',
      'Core practice drills for new racers',
      'Radio, goggles, and drone setup priorities',
      'How to read a race line',
      'First event expectations and etiquette',
    ],
    estimatedWordCount: 1600,
  },
  {
    slug: 'fpv-regulations-for-beginners-united-states',
    title: 'FPV Regulations for Beginners in the United States',
    category: 'Regulations',
    tier: 'support',
    audience: 'beginner',
    searchIntent: 'informational',
    primaryKeyword: 'FPV regulations United States',
    secondaryKeywords: [
      'Remote ID for FPV',
      'where can I fly FPV',
      'beginner drone rules US',
    ],
    seoTitle: 'FPV Regulations for Beginners in the United States',
    metaDescription:
      'Understand the basic U.S. FPV rules, Remote ID, and safe flying habits before your first pack.',
    summary:
      'A beginner-friendly overview of the U.S. FPV rules, with practical focus on safe flying habits and common compliance questions.',
    whyThisMatters:
      'Regulation content builds trust, protects new pilots, and supports future region-specific compliance articles.',
    outline: [
      'The basic legal frame for FPV flying in the U.S.',
      'Remote ID, location awareness, and common questions',
      'How to think about safe flying spots',
      'Recreational versus other use cases at a high level',
      'Where to verify current rules before flying',
    ],
    estimatedWordCount: 1500,
  },
  {
    slug: 'best-fpv-drones-for-beginners-buying-framework',
    title: 'Best FPV Drones for Beginners: A Practical Buying Framework',
    category: 'News and Reviews',
    tier: 'support',
    audience: 'beginner',
    searchIntent: 'commercial',
    primaryKeyword: 'best FPV drones for beginners',
    secondaryKeywords: ['beginner FPV drone', 'first FPV drone', 'RTF FPV kit'],
    seoTitle: 'Best FPV Drones for Beginners Buying Framework',
    metaDescription:
      'Choose a first FPV drone by skill level, indoor versus outdoor use, repairability, radio protocol, and upgrade path.',
    summary:
      'A buyer-intent guide that explains how beginners should compare whoops, toothpicks, cinewhoops, and starter kits without pretending to be hands-on testing.',
    whyThisMatters:
      'Beginner drone searches are high-intent affiliate pages and should route readers toward honest decision criteria before products.',
    outline: [
      'What makes a drone beginner-friendly',
      'TinyWhoop, toothpick, cinewhoop, and 5-inch tradeoffs',
      'RTF versus BNF versus DIY decision path',
      'Repairability, batteries, radio link, and spare parts',
      'Budget tiers and upgrade path',
    ],
    estimatedWordCount: 1900,
  },
  {
    slug: 'best-fpv-goggles-decision-guide-analog-dji-walksnail-hdzero',
    title: 'Best FPV Goggles Decision Guide: Analog, DJI, Walksnail, and HDZero',
    category: 'Components',
    tier: 'support',
    audience: 'beginner-to-intermediate',
    searchIntent: 'commercial',
    primaryKeyword: 'best FPV goggles',
    secondaryKeywords: ['DJI vs Walksnail goggles', 'analog FPV goggles', 'HDZero goggles'],
    seoTitle: 'Best FPV Goggles Decision Guide',
    metaDescription:
      'Compare FPV goggle ecosystems by latency, image quality, price, receiver support, and upgrade path.',
    summary:
      'A commercial comparison guide focused on ecosystem fit rather than fake rankings or unsupported hands-on claims.',
    whyThisMatters:
      'Goggles are a major purchase and a central affiliate category for FPVLovers.',
    outline: [
      'The ecosystem decision before the model decision',
      'Analog, DJI, Walksnail, and HDZero strengths',
      'Latency, penetration, recording, and comfort',
      'Budget and upgrade path',
      'Which pilot profile fits each ecosystem',
    ],
    estimatedWordCount: 1900,
  },
  {
    slug: 'best-fpv-radios-elrs-buying-guide',
    title: 'Best FPV Radios for ELRS Pilots: Buying Guide by Budget',
    category: 'Components',
    tier: 'support',
    audience: 'beginner-to-intermediate',
    searchIntent: 'commercial',
    primaryKeyword: 'best FPV radio ELRS',
    secondaryKeywords: ['best ELRS radio', 'Radiomaster radio guide', 'FPV transmitter buying guide'],
    seoTitle: 'Best FPV Radios for ELRS Pilots',
    metaDescription:
      'Choose an ELRS FPV radio by size, gimbals, battery format, module bay, screen, and long-term upgrade path.',
    summary:
      'A buyer guide for ELRS radios that helps pilots avoid buying twice while staying honest about product-fit criteria.',
    whyThisMatters:
      'Radio purchases are sticky, high-trust affiliate opportunities and support future ELRS educational content.',
    outline: [
      'Why ELRS changes the radio decision',
      'Gamepad versus full-size radio ergonomics',
      'Gimbals, switches, battery, and module bay',
      'Budget tiers for first-time and upgrading pilots',
      'Common mistakes before buying',
    ],
    estimatedWordCount: 1800,
  },
  {
    slug: 'fpv-starter-kits-by-budget-2026',
    title: 'FPV Starter Kits by Budget: What to Buy First in 2026',
    category: 'Build Guides',
    tier: 'support',
    audience: 'beginner',
    searchIntent: 'commercial',
    primaryKeyword: 'FPV starter kit budget',
    secondaryKeywords: ['FPV starter kit 2026', 'beginner FPV setup cost', 'FPV kit under budget'],
    seoTitle: 'FPV Starter Kits by Budget',
    metaDescription:
      'Plan a beginner FPV kit by budget, including radio, goggles, drone, charger, batteries, tools, and spares.',
    summary:
      'A practical kit-planning guide that turns beginner uncertainty into budget tiers and purchase order.',
    whyThisMatters:
      'Starter kit content connects tutorials, buyer guides, and affiliate CTAs without pretending to own every product.',
    outline: [
      'The purchase order that saves money',
      'Minimum viable simulator-first kit',
      'Indoor whoop kit budget',
      'Outdoor beginner kit budget',
      'Safety gear, spares, and hidden costs',
    ],
    estimatedWordCount: 2000,
  },
  {
    slug: 'best-lipo-chargers-for-fpv-safety-first-guide',
    title: 'Best LiPo Chargers for FPV: Safety-First Buying Guide',
    category: 'Components',
    tier: 'support',
    audience: 'beginner-to-intermediate',
    searchIntent: 'commercial',
    primaryKeyword: 'best LiPo charger for FPV',
    secondaryKeywords: ['FPV battery charger', 'LiPo balance charger', 'parallel charging FPV'],
    seoTitle: 'Best LiPo Chargers for FPV',
    metaDescription:
      'Understand FPV LiPo charger specs, balance charging, power supplies, wattage, and safety features before buying.',
    summary:
      'A safety-first commercial guide for charger selection that avoids risky oversimplification.',
    whyThisMatters:
      'Chargers are evergreen affiliate products and bad advice here can create real safety risk.',
    outline: [
      'What a LiPo charger must do',
      'Wattage, cell count, charge current, and power supply',
      'Balance charging and storage charging',
      'Parallel charging cautions',
      'Beginner-safe buying criteria',
    ],
    estimatedWordCount: 1800,
  },
  {
    slug: 'dji-o3-vs-walksnail-avatar-fpv-system-comparison',
    title: 'DJI O3 vs Walksnail Avatar: FPV System Comparison',
    category: 'Components',
    tier: 'support',
    audience: 'beginner-to-intermediate',
    searchIntent: 'comparative',
    primaryKeyword: 'DJI O3 vs Walksnail',
    secondaryKeywords: ['Walksnail vs DJI FPV', 'digital FPV system comparison', 'FPV video system'],
    seoTitle: 'DJI O3 vs Walksnail Avatar Comparison',
    metaDescription:
      'Compare DJI O3 and Walksnail Avatar by image quality, latency, air unit size, recording, cost, and build fit.',
    summary:
      'A comparison guide for digital FPV buyers based on decision criteria, not unsupported lab claims.',
    whyThisMatters:
      'This is a high-value comparison cluster that supports goggles, cinewhoop, and build content.',
    outline: [
      'The ecosystem choice',
      'Image quality and recording considerations',
      'Latency and racing suitability',
      'Air unit size, mounting, and heat',
      'Which system fits each pilot profile',
    ],
    estimatedWordCount: 1900,
  },
  {
    slug: 'elrs-radio-setup-guide-for-beginners',
    title: 'ELRS Radio Setup Guide for Beginners',
    category: 'Flight Guides',
    tier: 'support',
    audience: 'beginner',
    searchIntent: 'informational',
    primaryKeyword: 'ELRS radio setup',
    secondaryKeywords: ['ExpressLRS beginner guide', 'ELRS binding phrase', 'FPV radio setup'],
    seoTitle: 'ELRS Radio Setup Guide for Beginners',
    metaDescription:
      'Set up an ELRS radio with model profiles, binding phrase basics, packet rate concepts, and safe first checks.',
    summary:
      'A beginner-friendly ELRS setup guide that supports radio buyer guides and troubleshooting paths.',
    whyThisMatters:
      'ELRS is a core FPV protocol and creates strong internal linking across radio, receiver, and troubleshooting pages.',
    outline: [
      'What ELRS does in an FPV setup',
      'Binding phrase and model profile basics',
      'Packet rate and telemetry at a beginner level',
      'Common setup mistakes',
      'Pre-flight control link checks',
    ],
    estimatedWordCount: 1700,
  },
  {
    slug: 'cinewhoop-kit-buying-guide-for-indoor-and-real-estate-fpv',
    title: 'Cinewhoop Kit Buying Guide for Indoor and Real Estate FPV',
    category: 'Build Guides',
    tier: 'support',
    audience: 'beginner-to-intermediate',
    searchIntent: 'commercial',
    primaryKeyword: 'best cinewhoop kit',
    secondaryKeywords: ['cinewhoop for indoor video', 'real estate FPV drone', 'ducted FPV drone'],
    seoTitle: 'Cinewhoop Kit Buying Guide',
    metaDescription:
      'Choose a cinewhoop kit by prop size, duct design, camera system, payload, noise, safety, and indoor control needs.',
    summary:
      'A commercial cinewhoop guide for pilots comparing indoor, cinematic, and paid-shoot requirements.',
    whyThisMatters:
      'Cinewhoop content connects product discovery with cinematic FPV and creator monetization topics.',
    outline: [
      'What cinewhoops are good at',
      'Prop size, ducts, guards, and payload',
      'Analog versus digital camera systems',
      'Indoor safety and noise expectations',
      'Budget and upgrade considerations',
    ],
    estimatedWordCount: 1800,
  },
  {
    slug: 'long-range-fpv-setup-guide-safety-signal-and-power',
    title: 'Long-Range FPV Setup Guide: Safety, Signal, and Power',
    category: 'Build Guides',
    tier: 'support',
    audience: 'intermediate',
    searchIntent: 'informational',
    primaryKeyword: 'long range FPV setup',
    secondaryKeywords: ['long range FPV build', 'FPV GPS rescue', 'long range drone gear'],
    seoTitle: 'Long-Range FPV Setup Guide',
    metaDescription:
      'Plan a long-range FPV setup around signal reliability, GPS rescue, battery choice, antenna strategy, and legal awareness.',
    summary:
      'A serious long-range planning guide that prioritizes safety and system reliability over hype.',
    whyThisMatters:
      'Long-range FPV has strong search demand and requires careful, trust-building editorial handling.',
    outline: [
      'Why long-range setups need a different mindset',
      'Control link, video link, GPS, and failsafe planning',
      'Battery, prop, and efficiency tradeoffs',
      'Antenna placement and ground station basics',
      'Safety and regulation checkpoints',
    ],
    estimatedWordCount: 2100,
  },
  {
    slug: 'fpv-racing-gear-checklist-for-first-event',
    title: 'FPV Racing Gear Checklist for Your First Event',
    category: 'Racing',
    tier: 'support',
    audience: 'beginner',
    searchIntent: 'informational',
    primaryKeyword: 'FPV racing gear checklist',
    secondaryKeywords: ['first drone race checklist', 'FPV race day gear', 'drone racing tools'],
    seoTitle: 'FPV Racing Gear Checklist',
    metaDescription:
      'Prepare for a first FPV race with a practical checklist for batteries, props, tools, antennas, charging, and pit workflow.',
    summary:
      'A community-first race day checklist that helps new racers show up prepared without overbuying.',
    whyThisMatters:
      'Race checklist content creates internal links into tools, batteries, chargers, radios, and racing guides.',
    outline: [
      'Core drone and radio gear',
      'Batteries, charging, and pit power',
      'Props, tools, and repair supplies',
      'Video channel and antenna preparation',
      'Race-day etiquette and workflow',
    ],
    estimatedWordCount: 1600,
  },
  {
    slug: 'fpv-drone-toolkit-beginner-build-and-repair-checklist',
    title: 'FPV Drone Toolkit: Beginner Build and Repair Checklist',
    category: 'Build Guides',
    tier: 'support',
    audience: 'beginner',
    searchIntent: 'commercial',
    primaryKeyword: 'FPV drone toolkit',
    secondaryKeywords: ['FPV tools checklist', 'drone repair tools', 'FPV soldering tools'],
    seoTitle: 'FPV Drone Toolkit Checklist',
    metaDescription:
      'Build a practical FPV toolkit with drivers, soldering gear, smoke stopper, battery safety gear, and field repair basics.',
    summary:
      'A buying-intent tools checklist focused on safe building, bench testing, and field repairs.',
    whyThisMatters:
      'Tools are evergreen affiliate products and reduce beginner repair frustration.',
    outline: [
      'The minimum toolkit for a first FPV build',
      'Soldering and smoke stopper basics',
      'Field repair tools',
      'Battery safety accessories',
      'What beginners can skip at first',
    ],
    estimatedWordCount: 1700,
  },
  {
    slug: 'analog-vs-digital-fpv-for-beginners',
    title: 'Analog vs Digital FPV for Beginners: Which Video System Should You Choose?',
    category: 'Components',
    tier: 'support',
    audience: 'beginner',
    searchIntent: 'comparative',
    primaryKeyword: 'analog vs digital FPV',
    secondaryKeywords: ['digital FPV beginner', 'analog FPV beginner', 'FPV video system comparison'],
    seoTitle: 'Analog vs Digital FPV for Beginners',
    metaDescription:
      'Compare analog and digital FPV systems by cost, latency, image quality, durability, and upgrade path.',
    summary:
      'A beginner comparison that helps pilots pick a video path before buying goggles and drones.',
    whyThisMatters:
      'This is a gateway article for goggles, cinewhoops, racing, and digital ecosystem content.',
    outline: [
      'What analog and digital FPV mean',
      'Cost and upgrade path',
      'Latency and racing considerations',
      'Image quality and penetration',
      'Best fit by pilot profile',
    ],
    estimatedWordCount: 1700,
  },
  {
    slug: 'fpv-battery-buying-guide-cells-capacity-and-c-rating',
    title: 'FPV Battery Buying Guide: Cells, Capacity, and C-Rating Explained',
    category: 'Components',
    tier: 'support',
    audience: 'beginner',
    searchIntent: 'commercial',
    primaryKeyword: 'FPV battery buying guide',
    secondaryKeywords: ['FPV LiPo battery', '4S vs 6S FPV', 'LiPo C rating explained'],
    seoTitle: 'FPV Battery Buying Guide',
    metaDescription:
      'Choose FPV LiPo batteries by cell count, capacity, discharge rating, connector, weight, and flight style.',
    summary:
      'A safety-aware battery guide that supports charger, starter kit, and build compatibility pages.',
    whyThisMatters:
      'Battery selection is high-intent and safety-sensitive, making it important for trust and affiliate readiness.',
    outline: [
      'Cell count and voltage basics',
      'Capacity, weight, and flight time',
      'C-rating without marketing confusion',
      'Connector and charger compatibility',
      'Safe buying and storage habits',
    ],
    estimatedWordCount: 1800,
  },
  {
    slug: 'fpv-propeller-buying-guide-size-pitch-and-blade-count',
    title: 'FPV Propeller Buying Guide: Size, Pitch, and Blade Count',
    category: 'Components',
    tier: 'support',
    audience: 'beginner-to-intermediate',
    searchIntent: 'commercial',
    primaryKeyword: 'FPV propeller buying guide',
    secondaryKeywords: ['FPV props explained', 'prop pitch FPV', 'best props for 5 inch FPV'],
    seoTitle: 'FPV Propeller Buying Guide',
    metaDescription:
      'Understand FPV prop size, pitch, blade count, material, motor load, and flight style before buying spares.',
    summary:
      'A practical prop buying guide that connects performance, safety, and compatibility.',
    whyThisMatters:
      'Props are frequent purchases and a natural affiliate category with strong internal linking potential.',
    outline: [
      'How prop size and pitch affect feel',
      'Blade count and motor load',
      'Durability and material tradeoffs',
      'Matching props to drone size and motor KV',
      'How many spare props to keep',
    ],
    estimatedWordCount: 1600,
  },
  {
    slug: 'fpv-flight-controller-buying-guide-for-beginner-builds',
    title: 'FPV Flight Controller Buying Guide for Beginner Builds',
    category: 'Components',
    tier: 'support',
    audience: 'beginner-to-intermediate',
    searchIntent: 'commercial',
    primaryKeyword: 'FPV flight controller buying guide',
    secondaryKeywords: ['best flight controller FPV', 'FPV stack buying guide', 'Betaflight FC'],
    seoTitle: 'FPV Flight Controller Buying Guide',
    metaDescription:
      'Choose an FPV flight controller by firmware support, UARTs, gyro, mounting size, voltage support, and stack compatibility.',
    summary:
      'A component buying guide that explains selection criteria without inventing missing technical specs.',
    whyThisMatters:
      'Flight controllers are high-risk technical products and need source-backed, conservative guidance.',
    outline: [
      'What the flight controller does',
      'Firmware, UARTs, gyro, and mounting basics',
      'Stack compatibility and wiring needs',
      'Beginner mistakes when selecting an FC',
      'When to choose an AIO board',
    ],
    estimatedWordCount: 1800,
  },
  {
    slug: 'fpv-esc-buying-guide-current-rating-firmware-and-stack-fit',
    title: 'FPV ESC Buying Guide: Current Rating, Firmware, and Stack Fit',
    category: 'Components',
    tier: 'support',
    audience: 'beginner-to-intermediate',
    searchIntent: 'commercial',
    primaryKeyword: 'FPV ESC buying guide',
    secondaryKeywords: ['FPV 4 in 1 ESC', 'BLHeli ESC FPV', 'ESC current rating drone'],
    seoTitle: 'FPV ESC Buying Guide',
    metaDescription:
      'Choose an FPV ESC by current rating, voltage support, firmware, mounting, connector, and motor compatibility.',
    summary:
      'A conservative ESC selection guide focused on compatibility and safety margins.',
    whyThisMatters:
      'ESC mistakes can destroy hardware, so trustworthy buying guidance is essential.',
    outline: [
      'What an ESC does in an FPV build',
      'Current rating and safety margin',
      'Voltage, firmware, and telemetry basics',
      '4-in-1 versus individual ESCs',
      'Stack fit and wiring checks',
    ],
    estimatedWordCount: 1800,
  },
  {
    slug: 'fpv-antenna-guide-lhcp-rhcp-patch-and-omni',
    title: 'FPV Antenna Guide: LHCP, RHCP, Patch, and Omni Explained',
    category: 'Components',
    tier: 'support',
    audience: 'beginner',
    searchIntent: 'informational',
    primaryKeyword: 'FPV antenna guide',
    secondaryKeywords: ['LHCP vs RHCP', 'FPV patch antenna', 'FPV omni antenna'],
    seoTitle: 'FPV Antenna Guide',
    metaDescription:
      'Understand FPV antenna polarization, omni and patch patterns, placement, durability, and beginner buying mistakes.',
    summary:
      'An evergreen antenna guide that improves video-system decisions and troubleshooting.',
    whyThisMatters:
      'Antenna content supports goggles, VTX, long-range, and no-video troubleshooting clusters.',
    outline: [
      'What FPV antennas actually change',
      'LHCP and RHCP polarization',
      'Omni versus patch antenna patterns',
      'Drone placement and goggle setup',
      'Beginner buying mistakes',
    ],
    estimatedWordCount: 1600,
  },
] as const satisfies readonly ContentBrief[];

type EvergreenSeed = {
  slug: string;
  title: string;
  category: ContentCategory;
  audience: ContentBrief['audience'];
  searchIntent: ContentBrief['searchIntent'];
  primaryKeyword: string;
  secondaryKeywords: readonly string[];
  focus: string;
  outline: readonly string[];
  estimatedWordCount?: number;
};

function buildEvergreenBrief(seed: EvergreenSeed): ContentBrief {
  return {
    slug: seed.slug,
    title: seed.title,
    category: seed.category,
    tier: 'support',
    audience: seed.audience,
    searchIntent: seed.searchIntent,
    primaryKeyword: seed.primaryKeyword,
    secondaryKeywords: seed.secondaryKeywords,
    seoTitle: seed.title.length > 64 ? seed.title.slice(0, 61).trimEnd() : seed.title,
    metaDescription: `A practical FPV guide to ${seed.focus}, with conservative checks, source-aware decisions, and beginner-safe next steps.`,
    summary: `An evergreen FPVLovers guide focused on ${seed.focus}.`,
    whyThisMatters:
      'This expands the autonomous editorial backlog without first-person testing claims, fake partnerships, or unverified purchase recommendations.',
    outline: seed.outline,
    estimatedWordCount: seed.estimatedWordCount ?? 1700,
  };
}

const evergreenExpansionSeeds = [
  {
    slug: 'five-inch-freestyle-build-checklist',
    title: '5-Inch FPV Freestyle Build Checklist: Frame, Power, Video, and Spares',
    category: 'Build Guides',
    audience: 'beginner-to-intermediate',
    searchIntent: 'informational',
    primaryKeyword: '5 inch FPV freestyle build checklist',
    secondaryKeywords: ['5 inch FPV build', 'freestyle drone parts list', 'FPV build checklist'],
    focus: 'planning a reliable 5-inch freestyle build before buying parts',
    outline: ['Mission profile and frame size', 'Powertrain and battery assumptions', 'Video and radio link choices', 'Bench safety checks', 'Spare parts and field readiness'],
  },
  {
    slug: 'sub-250-fpv-build-guide-weight-budget-and-safety',
    title: 'Sub-250 FPV Build Guide: Weight Budget, Safety, and Component Choices',
    category: 'Build Guides',
    audience: 'beginner-to-intermediate',
    searchIntent: 'informational',
    primaryKeyword: 'sub 250 FPV build guide',
    secondaryKeywords: ['sub 250 drone build', 'lightweight FPV build', '250g FPV drone'],
    focus: 'building under 250 grams without hiding weight and safety tradeoffs',
    outline: ['Define the legal and practical weight target', 'Frame and prop size tradeoffs', 'Battery and payload limits', 'Durability compromises', 'Pre-flight safety checks'],
  },
  {
    slug: 'three-and-half-inch-cinewhoop-build-plan',
    title: '3.5-Inch Cinewhoop Build Plan: Indoor Control Without Overheating',
    category: 'Build Guides',
    audience: 'intermediate',
    searchIntent: 'informational',
    primaryKeyword: '3.5 inch cinewhoop build',
    secondaryKeywords: ['cinewhoop build plan', 'indoor FPV drone build', 'ducted FPV build'],
    focus: 'planning a ducted cinematic build with cooling, noise, and payload constraints',
    outline: ['When 3.5-inch makes sense', 'Ducts, payload, and motor load', 'Air unit cooling', 'Noise and indoor control', 'Testing before client-style flying'],
  },
  {
    slug: 'fpv-wiring-diagram-beginner-bench-map',
    title: 'FPV Wiring Diagram for Beginners: A Safe Bench Map Before Soldering',
    category: 'Build Guides',
    audience: 'beginner',
    searchIntent: 'informational',
    primaryKeyword: 'FPV wiring diagram beginner',
    secondaryKeywords: ['FPV drone wiring', 'flight controller wiring', 'FPV soldering map'],
    focus: 'turning wiring confusion into a safe bench plan',
    outline: ['Power path first', 'Signal wires and UART planning', 'Camera and VTX wiring', 'Receiver wiring', 'Continuity and smoke-stopper checks'],
  },
  {
    slug: 'fpv-stack-mounting-and-vibration-isolation-guide',
    title: 'FPV Stack Mounting and Vibration Isolation Guide',
    category: 'Build Guides',
    audience: 'beginner-to-intermediate',
    searchIntent: 'informational',
    primaryKeyword: 'FPV stack mounting guide',
    secondaryKeywords: ['flight controller soft mounting', 'FPV vibration isolation', 'drone stack build'],
    focus: 'mounting electronics so vibration does not become a tuning problem',
    outline: ['Stack height and screw planning', 'Soft mounting basics', 'Wire strain relief', 'Gyro noise symptoms', 'Inspection after crashes'],
  },
  {
    slug: 'gps-module-placement-for-fpv-builds',
    title: 'GPS Module Placement for FPV Builds: Signal, Noise, and Rescue Reliability',
    category: 'Build Guides',
    audience: 'intermediate',
    searchIntent: 'informational',
    primaryKeyword: 'FPV GPS module placement',
    secondaryKeywords: ['Betaflight GPS rescue', 'GPS rescue setup', 'FPV GPS interference'],
    focus: 'placing GPS hardware for reliable rescue behavior',
    outline: ['What GPS can and cannot solve', 'RF noise and antenna clearance', 'Mounting options', 'Betaflight sanity checks', 'Rescue test routine'],
  },
  {
    slug: 'fpv-smoke-stopper-first-power-up-protocol',
    title: 'FPV Smoke Stopper First Power-Up Protocol',
    category: 'Build Guides',
    audience: 'beginner',
    searchIntent: 'diagnostic',
    primaryKeyword: 'FPV smoke stopper first power up',
    secondaryKeywords: ['smoke stopper FPV', 'first power up drone', 'FPV bench safety'],
    focus: 'preventing avoidable electronics damage during first power-up',
    outline: ['Why first power-up is risky', 'Continuity check order', 'Smoke stopper behavior', 'USB versus LiPo checks', 'What to do when the limiter trips'],
  },
  {
    slug: 'quiet-cinewhoop-build-for-indoor-filming',
    title: 'Quiet Cinewhoop Build for Indoor Filming: Noise, Props, and Ducts',
    category: 'Build Guides',
    audience: 'intermediate',
    searchIntent: 'informational',
    primaryKeyword: 'quiet cinewhoop build',
    secondaryKeywords: ['indoor cinewhoop noise', 'quiet FPV props', 'real estate FPV drone'],
    focus: 'reducing indoor cinewhoop noise without making unsafe assumptions',
    outline: ['Why cinewhoops get loud', 'Prop and duct effects', 'Motor load and battery choice', 'Tuning expectations', 'Indoor safety workflow'],
  },
  {
    slug: 'field-repair-kit-for-fpv-pilots',
    title: 'Field Repair Kit for FPV Pilots: What to Carry Without Overpacking',
    category: 'Build Guides',
    audience: 'beginner',
    searchIntent: 'commercial',
    primaryKeyword: 'FPV field repair kit',
    secondaryKeywords: ['FPV tools field kit', 'drone repair kit', 'FPV race day tools'],
    focus: 'building a practical repair kit for real flying days',
    outline: ['Core hand tools', 'Electrical repair basics', 'Props and hardware', 'Battery and charging safety', 'What can stay at home'],
  },
  {
    slug: 'fpv-action-camera-mounting-guide',
    title: 'FPV Action Camera Mounting Guide: Angle, Jello, and Crash Protection',
    category: 'Build Guides',
    audience: 'beginner-to-intermediate',
    searchIntent: 'informational',
    primaryKeyword: 'FPV action camera mounting',
    secondaryKeywords: ['GoPro FPV mount', 'FPV camera angle', 'FPV jello vibration'],
    focus: 'mounting an action camera without compromising flight or footage',
    outline: ['Camera angle by flying style', 'Vibration and jello control', 'TPU mount tradeoffs', 'Crash protection', 'Pre-flight inspection'],
  },
  {
    slug: 'motor-kv-vs-prop-size-explained-for-fpv',
    title: 'Motor KV vs Prop Size Explained for FPV Builds',
    category: 'Components',
    audience: 'beginner',
    searchIntent: 'informational',
    primaryKeyword: 'motor KV vs prop size FPV',
    secondaryKeywords: ['FPV motor KV explained', 'prop size motor matching', 'drone motor guide'],
    focus: 'matching motor KV and prop size conservatively',
    outline: ['What KV really means', 'Prop diameter and pitch load', 'Voltage and heat', 'Why bigger is not always better', 'Safe matching habits'],
  },
  {
    slug: 'four-in-one-esc-vs-individual-escs',
    title: '4-in-1 ESC vs Individual ESCs: FPV Build Tradeoffs',
    category: 'Components',
    audience: 'beginner-to-intermediate',
    searchIntent: 'comparative',
    primaryKeyword: '4 in 1 ESC vs individual ESC',
    secondaryKeywords: ['FPV ESC comparison', 'drone ESC guide', '4 in 1 ESC FPV'],
    focus: 'choosing ESC architecture by repairability, wiring, and space',
    outline: ['How each ESC layout works', 'Wiring complexity', 'Repair and crash damage', 'Stack fit', 'Which builds fit each option'],
  },
  {
    slug: 'fpv-capacitor-sizing-and-placement-guide',
    title: 'FPV Capacitor Sizing and Placement Guide',
    category: 'Components',
    audience: 'beginner-to-intermediate',
    searchIntent: 'informational',
    primaryKeyword: 'FPV capacitor sizing',
    secondaryKeywords: ['drone capacitor guide', 'ESC capacitor FPV', 'FPV electrical noise'],
    focus: 'using capacitors to reduce electrical noise without guessing',
    outline: ['What capacitors do', 'Voltage rating basics', 'Placement near the ESC', 'Symptoms of electrical noise', 'Inspection and replacement'],
  },
  {
    slug: 'vtx-power-levels-explained-for-fpv',
    title: 'VTX Power Levels Explained for FPV: Range, Heat, and Rules',
    category: 'Components',
    audience: 'beginner',
    searchIntent: 'informational',
    primaryKeyword: 'FPV VTX power levels',
    secondaryKeywords: ['VTX mW explained', 'FPV video range', 'VTX overheating'],
    focus: 'choosing video transmitter power with heat and rules in mind',
    outline: ['What VTX power changes', 'Heat on the bench', 'Antenna quality versus power', 'Race and group flying etiquette', 'Legal and local rule checks'],
  },
  {
    slug: 'digital-air-unit-cooling-guide',
    title: 'Digital FPV Air Unit Cooling Guide: Bench Time, Mounting, and Airflow',
    category: 'Components',
    audience: 'beginner-to-intermediate',
    searchIntent: 'diagnostic',
    primaryKeyword: 'digital FPV air unit cooling',
    secondaryKeywords: ['DJI O3 overheating', 'Walksnail cooling', 'FPV air unit heat'],
    focus: 'preventing digital video overheating during setup and flight',
    outline: ['Why air units heat up', 'Bench cooling workflow', 'Mounting and airflow', 'Firmware setup habits', 'Warning signs to stop'],
  },
  {
    slug: 'elrs-receiver-antenna-placement-guide',
    title: 'ELRS Receiver Antenna Placement Guide for FPV Builds',
    category: 'Components',
    audience: 'beginner-to-intermediate',
    searchIntent: 'informational',
    primaryKeyword: 'ELRS receiver antenna placement',
    secondaryKeywords: ['ExpressLRS antenna mounting', 'FPV receiver antenna', 'ELRS range tips'],
    focus: 'placing receiver antennas for durable signal behavior',
    outline: ['Antenna orientation basics', 'Carbon and battery shadowing', 'Mount durability', 'Telemetry warning signs', 'Post-crash checks'],
  },
  {
    slug: 'fpv-radio-gimbals-switches-and-ergonomics-guide',
    title: 'FPV Radio Gimbals, Switches, and Ergonomics Guide',
    category: 'Components',
    audience: 'beginner',
    searchIntent: 'commercial',
    primaryKeyword: 'FPV radio ergonomics',
    secondaryKeywords: ['radio gimbals FPV', 'FPV transmitter guide', 'gamepad vs full size radio'],
    focus: 'choosing radio ergonomics before chasing specs',
    outline: ['Grip style and hand size', 'Gimbal feel and maintenance', 'Switch layout', 'Module bay needs', 'Long-term comfort'],
  },
  {
    slug: 'xt30-vs-xt60-for-fpv-batteries',
    title: 'XT30 vs XT60 for FPV Batteries: Connector Choice Without Guesswork',
    category: 'Components',
    audience: 'beginner',
    searchIntent: 'comparative',
    primaryKeyword: 'XT30 vs XT60 FPV',
    secondaryKeywords: ['FPV battery connector', 'XT30 connector drone', 'XT60 connector drone'],
    focus: 'matching battery connectors to current draw and build size',
    outline: ['Connector role in the power path', 'Small drones and XT30', '5-inch builds and XT60', 'Adapter cautions', 'Inspection and soldering quality'],
  },
  {
    slug: 'fpv-prop-material-durability-guide',
    title: 'FPV Prop Material and Durability Guide',
    category: 'Components',
    audience: 'beginner',
    searchIntent: 'commercial',
    primaryKeyword: 'FPV prop durability',
    secondaryKeywords: ['FPV prop material', 'durable drone props', 'propeller buying guide'],
    focus: 'choosing prop durability by skill level and flying style',
    outline: ['Material stiffness and feel', 'Crash durability', 'Noise and efficiency', 'When to replace props', 'How many spares to buy'],
  },
  {
    slug: 'flight-controller-uart-planning-guide',
    title: 'Flight Controller UART Planning Guide for FPV Builders',
    category: 'Components',
    audience: 'beginner-to-intermediate',
    searchIntent: 'informational',
    primaryKeyword: 'flight controller UART planning',
    secondaryKeywords: ['FPV UART guide', 'Betaflight UART setup', 'flight controller ports'],
    focus: 'planning FC ports before wiring receivers, GPS, and VTX control',
    outline: ['What a UART is', 'Receiver, GPS, and VTX control needs', 'SoftSerial cautions', 'Documentation checks', 'A simple planning worksheet'],
  },
  {
    slug: 'fpv-antenna-placement-on-frames',
    title: 'FPV Antenna Placement on Frames: Video, Radio, and GPS Separation',
    category: 'Components',
    audience: 'beginner-to-intermediate',
    searchIntent: 'informational',
    primaryKeyword: 'FPV antenna placement',
    secondaryKeywords: ['FPV antenna mounting', 'radio antenna placement', 'video antenna placement'],
    focus: 'separating antennas so the build is durable and signal-aware',
    outline: ['Video antenna clearance', 'Receiver antenna orientation', 'GPS separation', 'Crash protection', 'Range test habits'],
  },
  {
    slug: 'fpv-hd-recording-options-guide',
    title: 'FPV HD Recording Options: Action Cameras, Air Units, and DVR',
    category: 'Components',
    audience: 'beginner-to-intermediate',
    searchIntent: 'comparative',
    primaryKeyword: 'FPV HD recording options',
    secondaryKeywords: ['FPV DVR vs GoPro', 'DJI O3 recording', 'action camera FPV'],
    focus: 'choosing recording methods by weight, quality, and reliability',
    outline: ['What each recording option captures', 'Weight and battery impact', 'Image quality expectations', 'Crash risk', 'Workflow for reviewing footage'],
  },
  {
    slug: 'fpv-simulator-practice-plan-first-30-days',
    title: 'FPV Simulator Practice Plan: First 30 Days',
    category: 'Flight Guides',
    audience: 'beginner',
    searchIntent: 'informational',
    primaryKeyword: 'FPV simulator practice plan',
    secondaryKeywords: ['FPV simulator drills', 'learn acro mode', 'FPV training plan'],
    focus: 'using simulator time with structure instead of random flying',
    outline: ['Week one stick control', 'Turns and altitude control', 'Gate practice', 'Crash review habits', 'When to fly the real drone'],
  },
  {
    slug: 'acro-stick-control-drills-for-fpv-beginners',
    title: 'Acro Stick Control Drills for FPV Beginners',
    category: 'Flight Guides',
    audience: 'beginner',
    searchIntent: 'informational',
    primaryKeyword: 'FPV acro stick control drills',
    secondaryKeywords: ['acro mode beginner', 'FPV control drills', 'learn FPV acro'],
    focus: 'building acro control before risky outdoor flights',
    outline: ['Throttle control', 'Pitch and roll balance', 'Yaw coordination', 'Recovery drills', 'Session structure'],
  },
  {
    slug: 'first-outdoor-fpv-flight-checklist',
    title: 'First Outdoor FPV Flight Checklist',
    category: 'Flight Guides',
    audience: 'beginner',
    searchIntent: 'informational',
    primaryKeyword: 'first outdoor FPV flight checklist',
    secondaryKeywords: ['first FPV flight', 'FPV preflight checklist', 'beginner drone flight'],
    focus: 'moving from simulator or indoor whoop to a controlled outdoor session',
    outline: ['Site and weather checks', 'Battery and radio checks', 'Failsafe confirmation', 'First hover and circuits', 'Pack review after landing'],
  },
  {
    slug: 'fpv-wind-management-for-lightweight-drones',
    title: 'FPV Wind Management for Lightweight Drones',
    category: 'Flight Guides',
    audience: 'beginner-to-intermediate',
    searchIntent: 'informational',
    primaryKeyword: 'FPV wind management',
    secondaryKeywords: ['fly FPV in wind', 'lightweight drone wind', 'FPV weather guide'],
    focus: 'reading wind before flying small FPV drones',
    outline: ['When wind is too much', 'Gusts near trees and buildings', 'Battery impact', 'Landing approach', 'Abort decisions'],
  },
  {
    slug: 'fpv-landing-approach-practice-guide',
    title: 'FPV Landing Approach Practice Guide',
    category: 'Flight Guides',
    audience: 'beginner',
    searchIntent: 'informational',
    primaryKeyword: 'FPV landing practice',
    secondaryKeywords: ['land FPV drone', 'FPV landing drills', 'beginner FPV flying'],
    focus: 'making landings repeatable instead of panic-driven',
    outline: ['Pick a landing zone', 'Approach angle', 'Throttle reduction', 'Disarm timing', 'Post-landing inspection'],
  },
  {
    slug: 'fpv-failsafe-test-routine-before-flying',
    title: 'FPV Failsafe Test Routine Before Flying',
    category: 'Flight Guides',
    audience: 'beginner-to-intermediate',
    searchIntent: 'diagnostic',
    primaryKeyword: 'FPV failsafe test routine',
    secondaryKeywords: ['Betaflight failsafe test', 'ELRS failsafe', 'drone failsafe setup'],
    focus: 'testing failsafe behavior before trusting a build outdoors',
    outline: ['What failsafe should do', 'Bench test safety', 'Receiver and flight controller settings', 'GPS rescue considerations', 'When not to fly'],
  },
  {
    slug: 'cinematic-fpv-reveal-shot-guide',
    title: 'Cinematic FPV Reveal Shot Guide: Planning, Speed, and Safety',
    category: 'Flight Guides',
    audience: 'intermediate',
    searchIntent: 'informational',
    primaryKeyword: 'cinematic FPV reveal shot',
    secondaryKeywords: ['FPV cinematic shots', 'FPV filming guide', 'drone reveal shot'],
    focus: 'planning cinematic reveals with safe repeatable flight paths',
    outline: ['Define the subject', 'Approach and exit line', 'Speed control', 'Spotter and site safety', 'Reviewing footage'],
  },
  {
    slug: 'fpv-battery-sag-flight-management',
    title: 'FPV Battery Sag: How to Manage Voltage in Flight',
    category: 'Flight Guides',
    audience: 'beginner',
    searchIntent: 'diagnostic',
    primaryKeyword: 'FPV battery sag',
    secondaryKeywords: ['LiPo voltage sag FPV', 'FPV battery warning', 'drone voltage drop'],
    focus: 'understanding voltage sag without over-discharging packs',
    outline: ['What sag feels like', 'OSD voltage habits', 'Throttle and current draw', 'Landing thresholds', 'Battery health checks'],
  },
  {
    slug: 'fpv-drone-wont-arm-troubleshooting',
    title: "FPV Drone Won't Arm: Betaflight Troubleshooting Checklist",
    category: 'Troubleshooting',
    audience: 'beginner',
    searchIntent: 'diagnostic',
    primaryKeyword: "FPV drone won't arm",
    secondaryKeywords: ['Betaflight arming disabled', 'drone not arming', 'FPV arm switch problem'],
    focus: 'isolating Betaflight arming blocks safely',
    outline: ['Read arming disable flags', 'Radio and modes checks', 'Throttle and accelerometer issues', 'GPS and failsafe blocks', 'Safe bench workflow'],
  },
  {
    slug: 'receiver-tab-no-movement-in-betaflight',
    title: 'Receiver Tab No Movement in Betaflight: ELRS and Radio Checks',
    category: 'Troubleshooting',
    audience: 'beginner',
    searchIntent: 'diagnostic',
    primaryKeyword: 'Betaflight receiver tab no movement',
    secondaryKeywords: ['ELRS receiver not working', 'Betaflight radio setup', 'FPV receiver troubleshooting'],
    focus: 'diagnosing receiver input problems without replacing parts too early',
    outline: ['Bind and model match', 'UART and serial receiver settings', 'Protocol selection', 'Radio output checks', 'When hardware is suspect'],
  },
  {
    slug: 'fpv-motor-spins-wrong-direction-fix',
    title: 'FPV Motor Spins the Wrong Direction: Safe Fix Checklist',
    category: 'Troubleshooting',
    audience: 'beginner',
    searchIntent: 'diagnostic',
    primaryKeyword: 'FPV motor spins wrong direction',
    secondaryKeywords: ['Betaflight motor direction', 'ESC motor direction', 'props in props out'],
    focus: 'fixing motor direction with props removed and clear safety steps',
    outline: ['Remove props first', 'Motor order versus direction', 'Betaflight motor test', 'ESC configurator options', 'Final props-in or props-out check'],
  },
  {
    slug: 'black-screen-after-fpv-crash',
    title: 'Black Screen After an FPV Crash: Camera, VTX, and Cable Checks',
    category: 'Troubleshooting',
    audience: 'beginner-to-intermediate',
    searchIntent: 'diagnostic',
    primaryKeyword: 'black screen after FPV crash',
    secondaryKeywords: ['FPV camera black screen', 'VTX no video after crash', 'FPV video troubleshooting'],
    focus: 'recovering video after impact without random part swaps',
    outline: ['Start with antenna and channel', 'Inspect camera cable', 'Power rail checks', 'VTX status lights', 'Bench isolation'],
  },
  {
    slug: 'fpv-vtx-overheats-on-bench',
    title: 'FPV VTX Overheats on the Bench: Cooling and Setup Checklist',
    category: 'Troubleshooting',
    audience: 'beginner',
    searchIntent: 'diagnostic',
    primaryKeyword: 'FPV VTX overheats on bench',
    secondaryKeywords: ['VTX overheating FPV', 'video transmitter heat', 'FPV bench fan'],
    focus: 'preventing heat damage during setup',
    outline: ['Why VTX units heat up', 'Use a fan during setup', 'Lower power modes', 'Antenna requirements', 'Stop signs and cooldown'],
  },
  {
    slug: 'osd-missing-in-fpv-goggles',
    title: 'OSD Missing in FPV Goggles: Betaflight and Video Path Checks',
    category: 'Troubleshooting',
    audience: 'beginner',
    searchIntent: 'diagnostic',
    primaryKeyword: 'OSD missing FPV goggles',
    secondaryKeywords: ['Betaflight OSD not showing', 'FPV OSD troubleshooting', 'no OSD drone'],
    focus: 'separating camera video from flight-controller OSD issues',
    outline: ['Confirm video exists', 'PAL/NTSC and digital OSD differences', 'Betaflight OSD tab', 'Wiring through FC', 'When the camera bypasses OSD'],
  },
  {
    slug: 'gps-rescue-not-activating-troubleshooting',
    title: 'GPS Rescue Not Activating: FPV Troubleshooting Checklist',
    category: 'Troubleshooting',
    audience: 'intermediate',
    searchIntent: 'diagnostic',
    primaryKeyword: 'GPS rescue not activating',
    secondaryKeywords: ['Betaflight GPS rescue troubleshooting', 'FPV GPS rescue setup', 'GPS rescue failsafe'],
    focus: 'checking GPS rescue prerequisites before relying on it',
    outline: ['Satellite and home point requirements', 'Mode and failsafe configuration', 'Compass expectations', 'Test conditions', 'When manual recovery is safer'],
  },
  {
    slug: 'elrs-telemetry-lost-warning-guide',
    title: 'ELRS Telemetry Lost Warning: What to Check Before Flying Again',
    category: 'Troubleshooting',
    audience: 'beginner-to-intermediate',
    searchIntent: 'diagnostic',
    primaryKeyword: 'ELRS telemetry lost warning',
    secondaryKeywords: ['ExpressLRS telemetry lost', 'ELRS warning FPV', 'FPV radio telemetry'],
    focus: 'understanding telemetry warnings without ignoring real link risks',
    outline: ['Telemetry versus control link', 'Antenna and receiver checks', 'Packet rate and power', 'Range test', 'When to stop flying'],
  },
  {
    slug: 'random-failsafe-fpv-diagnosis',
    title: 'Random FPV Failsafe Diagnosis: Radio Link, Power, and Antenna Checks',
    category: 'Troubleshooting',
    audience: 'intermediate',
    searchIntent: 'diagnostic',
    primaryKeyword: 'random FPV failsafe',
    secondaryKeywords: ['FPV failsafe troubleshooting', 'ELRS failsafe problem', 'drone loses signal'],
    focus: 'diagnosing intermittent failsafe events from evidence',
    outline: ['Record the exact context', 'Radio link logs and warnings', 'Power brownout checks', 'Antenna damage', 'Controlled retest plan'],
  },
  {
    slug: 'hot-motors-after-fpv-tuning',
    title: 'Hot Motors After FPV Tuning: Filter, Prop, and PID Checks',
    category: 'Troubleshooting',
    audience: 'intermediate',
    searchIntent: 'diagnostic',
    primaryKeyword: 'hot motors after FPV tuning',
    secondaryKeywords: ['Betaflight hot motors', 'FPV tuning troubleshooting', 'motor heat drone'],
    focus: 'treating motor heat as a stop-and-diagnose signal',
    outline: ['Stop before damage', 'Prop and mechanical checks', 'Filter changes', 'D-term and noise', 'Short controlled test flights'],
  },
  {
    slug: 'fpv-practice-gates-home-setup',
    title: 'FPV Practice Gates at Home: A Beginner Training Setup',
    category: 'Racing',
    audience: 'beginner',
    searchIntent: 'informational',
    primaryKeyword: 'FPV practice gates home',
    secondaryKeywords: ['FPV racing practice', 'drone racing gates', 'FPV training course'],
    focus: 'building a simple practice course for consistent skill growth',
    outline: ['Space and safety', 'Gate size and spacing', 'Beginner drills', 'Timing progress', 'Avoiding bad habits'],
  },
  {
    slug: 'fpv-race-battery-strategy',
    title: 'FPV Race Battery Strategy: Packs, Charging, and Heat Management',
    category: 'Racing',
    audience: 'beginner-to-intermediate',
    searchIntent: 'informational',
    primaryKeyword: 'FPV race battery strategy',
    secondaryKeywords: ['race day LiPo charging', 'FPV racing batteries', 'drone race packs'],
    focus: 'planning batteries for race-day reliability',
    outline: ['How many packs to bring', 'Charging workflow', 'Voltage and heat', 'Labeling and rotation', 'Post-race storage'],
  },
  {
    slug: 'fpv-video-channel-management-race-day',
    title: 'FPV Video Channel Management on Race Day',
    category: 'Racing',
    audience: 'beginner-to-intermediate',
    searchIntent: 'informational',
    primaryKeyword: 'FPV video channel management',
    secondaryKeywords: ['FPV race channels', 'VTX pit mode', 'drone racing video interference'],
    focus: 'avoiding video interference in group racing',
    outline: ['Why channel discipline matters', 'Pit mode habits', 'Race director instructions', 'Antenna and power checks', 'What to do when video breaks up'],
  },
  {
    slug: 'fpv-race-tech-inspection-checklist',
    title: 'FPV Race Tech Inspection Checklist for New Pilots',
    category: 'Racing',
    audience: 'beginner',
    searchIntent: 'informational',
    primaryKeyword: 'FPV race tech inspection',
    secondaryKeywords: ['drone race checklist', 'FPV racing rules', 'race day drone inspection'],
    focus: 'arriving at a race with a build that can pass basic checks',
    outline: ['Frame and prop condition', 'Failsafe and arming', 'Video setup', 'Battery safety', 'Documentation and event rules'],
  },
  {
    slug: 'remote-id-basics-for-fpv-builders',
    title: 'Remote ID Basics for FPV Builders',
    category: 'Regulations',
    audience: 'beginner',
    searchIntent: 'informational',
    primaryKeyword: 'Remote ID basics FPV',
    secondaryKeywords: ['Remote ID drone', 'FPV Remote ID module', 'drone rules beginners'],
    focus: 'understanding Remote ID as a builder without legal overclaiming',
    outline: ['What Remote ID is', 'Recreational context', 'Module considerations', 'Where to verify rules', 'Practical pre-flight habits'],
  },
  {
    slug: 'where-to-fly-fpv-legally-beginner-guide',
    title: 'Where to Fly FPV Legally: Beginner Site Selection Guide',
    category: 'Regulations',
    audience: 'beginner',
    searchIntent: 'informational',
    primaryKeyword: 'where to fly FPV legally',
    secondaryKeywords: ['FPV flying spots', 'drone airspace beginner', 'legal FPV locations'],
    focus: 'choosing safer legal flying spots with current-rule verification',
    outline: ['Start with airspace checks', 'People and property separation', 'Club fields and parks', 'Visual observer expectations', 'Documenting your decision'],
  },
  {
    slug: 'fpv-visual-observer-spotter-guide',
    title: 'FPV Visual Observer and Spotter Guide',
    category: 'Regulations',
    audience: 'beginner',
    searchIntent: 'informational',
    primaryKeyword: 'FPV visual observer guide',
    secondaryKeywords: ['FPV spotter', 'visual observer drone', 'FPV safety rules'],
    focus: 'using a spotter as a real safety layer',
    outline: ['What a visual observer watches', 'Communication before takeoff', 'Airspace and people checks', 'Emergency calls', 'Post-flight review'],
  },
  {
    slug: 'beginner-fpv-cost-breakdown',
    title: 'Beginner FPV Cost Breakdown: What the First Setup Really Includes',
    category: 'News and Reviews',
    audience: 'beginner',
    searchIntent: 'commercial',
    primaryKeyword: 'beginner FPV cost breakdown',
    secondaryKeywords: ['FPV setup cost', 'how much does FPV cost', 'beginner drone budget'],
    focus: 'explaining real startup costs without fake deal claims',
    outline: ['Simulator-first minimum', 'Radio, goggles, and drone', 'Batteries and charger', 'Tools and spares', 'Where beginners overspend'],
  },
  {
    slug: 'used-fpv-gear-buying-checklist',
    title: 'Used FPV Gear Buying Checklist: What to Inspect Before Paying',
    category: 'News and Reviews',
    audience: 'beginner-to-intermediate',
    searchIntent: 'commercial',
    primaryKeyword: 'used FPV gear buying checklist',
    secondaryKeywords: ['buy used FPV drone', 'used FPV goggles', 'used FPV radio'],
    focus: 'reducing used-gear risk with inspection habits',
    outline: ['Ask for exact model and photos', 'Battery and crash history', 'Firmware and binding risks', 'Missing parts', 'When to walk away'],
  },
  {
    slug: 'analog-fpv-still-worth-it-guide',
    title: 'Is Analog FPV Still Worth It? A Practical Beginner Guide',
    category: 'News and Reviews',
    audience: 'beginner',
    searchIntent: 'comparative',
    primaryKeyword: 'is analog FPV still worth it',
    secondaryKeywords: ['analog FPV 2026', 'digital vs analog FPV', 'budget FPV video'],
    focus: 'judging analog FPV by budget, latency, repairability, and learning goals',
    outline: ['Where analog still wins', 'Where digital is easier', 'Cost and repairability', 'Racing and latency', 'Best fit by pilot profile'],
  },
  {
    slug: 'fpv-learning-path-first-90-days',
    title: 'FPV Learning Path: Your First 90 Days From Simulator to Confident Flights',
    category: 'Flight Guides',
    audience: 'beginner',
    searchIntent: 'informational',
    primaryKeyword: 'FPV learning path',
    secondaryKeywords: ['learn FPV in 90 days', 'FPV beginner roadmap', 'FPV practice plan'],
    focus: 'turning beginner progress into a structured 90-day roadmap',
    outline: ['Days 1-14 simulator basics', 'First hardware decisions', 'First hover and circuits', 'Troubleshooting skills', 'When to upgrade'],
    estimatedWordCount: 2200,
  },
  {
    slug: 'fpv-club-safety-checklist',
    title: 'FPV Club Safety Checklist for Group Flying Days',
    category: 'Racing',
    audience: 'beginner-to-intermediate',
    searchIntent: 'informational',
    primaryKeyword: 'FPV club safety checklist',
    secondaryKeywords: ['group FPV flying', 'FPV safety checklist', 'drone club rules'],
    focus: 'making group flying safer and easier to organize',
    outline: ['Pilot briefing', 'Video channel control', 'Battery charging area', 'Spectator boundaries', 'Incident review'],
  },
  {
    slug: 'fpv-preflight-checklist-printable',
    title: 'FPV Preflight Checklist: A Practical Repeatable Routine',
    category: 'Flight Guides',
    audience: 'beginner',
    searchIntent: 'informational',
    primaryKeyword: 'FPV preflight checklist',
    secondaryKeywords: ['drone preflight checklist', 'FPV safety checks', 'before flying FPV'],
    focus: 'making preflight checks fast enough to actually use',
    outline: ['Airframe and props', 'Battery and straps', 'Radio and video link', 'Failsafe and GPS', 'Takeoff decision'],
  },
  {
    slug: 'fpv-post-crash-inspection-checklist',
    title: 'FPV Post-Crash Inspection Checklist',
    category: 'Troubleshooting',
    audience: 'beginner',
    searchIntent: 'diagnostic',
    primaryKeyword: 'FPV post crash inspection',
    secondaryKeywords: ['FPV crash checklist', 'drone crash repair', 'inspect FPV drone after crash'],
    focus: 'finding hidden crash damage before the next pack',
    outline: ['Disconnect and inspect safely', 'Props, frame, and motors', 'Stack and wires', 'Antenna and camera', 'Short hover retest'],
  },
  {
    slug: 'fpv-battery-storage-at-home-guide',
    title: 'FPV Battery Storage at Home: Safer Habits for LiPo Packs',
    category: 'Components',
    audience: 'beginner',
    searchIntent: 'informational',
    primaryKeyword: 'FPV battery storage',
    secondaryKeywords: ['LiPo storage safety', 'FPV LiPo storage', 'drone battery safety'],
    focus: 'storing LiPo batteries with conservative safety habits',
    outline: ['Storage voltage basics', 'Fire-resistant location', 'Damaged pack decisions', 'Labeling and rotation', 'What not to do'],
  },
  {
    slug: 'fpv-charger-wattage-explained',
    title: 'FPV Charger Wattage Explained: Match Charger, PSU, and Packs',
    category: 'Components',
    audience: 'beginner-to-intermediate',
    searchIntent: 'commercial',
    primaryKeyword: 'FPV charger wattage explained',
    secondaryKeywords: ['LiPo charger wattage', 'FPV charger power supply', 'parallel charging wattage'],
    focus: 'understanding charger wattage before buying or parallel charging',
    outline: ['Watts, volts, and amps', 'Power supply limits', 'Single-pack charging', 'Parallel charging cautions', 'Beginner-safe choices'],
  },
  {
    slug: 'fpv-frame-size-comparison-2-5-3-5-5-inch',
    title: 'FPV Frame Size Comparison: 2.5, 3.5, and 5-Inch Builds',
    category: 'Components',
    audience: 'beginner',
    searchIntent: 'comparative',
    primaryKeyword: 'FPV frame size comparison',
    secondaryKeywords: ['2.5 inch vs 5 inch FPV', '3.5 inch FPV drone', 'FPV frame size guide'],
    focus: 'matching frame size to space, payload, safety, and learning goals',
    outline: ['Indoor and outdoor space', 'Payload and wind', 'Durability and cost', 'Noise and safety', 'Best fit by pilot profile'],
  },
  {
    slug: 'fpv-stack-vs-aio-flight-controller',
    title: 'FPV Stack vs AIO Flight Controller: Which Build Path Fits You?',
    category: 'Components',
    audience: 'beginner-to-intermediate',
    searchIntent: 'comparative',
    primaryKeyword: 'FPV stack vs AIO',
    secondaryKeywords: ['AIO flight controller FPV', 'FPV stack guide', 'drone FC ESC stack'],
    focus: 'choosing between compact AIO boards and separate stack layouts',
    outline: ['What stack and AIO mean', 'Space and weight', 'Repairability', 'Current and heat', 'Who should choose each path'],
  },
  {
    slug: 'fpv-bench-testing-sequence',
    title: 'FPV Bench Testing Sequence: From USB to First Hover',
    category: 'Build Guides',
    audience: 'beginner',
    searchIntent: 'diagnostic',
    primaryKeyword: 'FPV bench testing sequence',
    secondaryKeywords: ['FPV first hover checklist', 'drone bench test', 'Betaflight setup checks'],
    focus: 'testing a new build in the right order',
    outline: ['USB-only configuration', 'Continuity and smoke stopper', 'Receiver and modes', 'Motor order and direction', 'Controlled first hover'],
  },
  {
    slug: 'fpv-radio-binding-phrase-mistakes',
    title: 'FPV Radio Binding Phrase Mistakes: ELRS Setup Troubleshooting',
    category: 'Troubleshooting',
    audience: 'beginner',
    searchIntent: 'diagnostic',
    primaryKeyword: 'ELRS binding phrase mistakes',
    secondaryKeywords: ['ELRS binding phrase', 'ExpressLRS bind issue', 'FPV radio binding'],
    focus: 'fixing common ELRS binding phrase and model-match mistakes',
    outline: ['Binding phrase basics', 'Firmware target match', 'Model profile checks', 'Receiver LED clues', 'When to reflash'],
  },
  {
    slug: 'fpv-video-breakup-near-ground',
    title: 'FPV Video Breakup Near the Ground: Multipath, Antennas, and Line of Sight',
    category: 'Troubleshooting',
    audience: 'beginner-to-intermediate',
    searchIntent: 'diagnostic',
    primaryKeyword: 'FPV video breakup near ground',
    secondaryKeywords: ['FPV multipath', 'video breakup FPV', 'FPV antenna troubleshooting'],
    focus: 'diagnosing video breakup with environment and antenna evidence',
    outline: ['What breakup looks like', 'Ground reflections and obstacles', 'Antenna orientation', 'Receiver diversity', 'Controlled test route'],
  },
  {
    slug: 'fpv-range-test-before-long-range',
    title: 'FPV Range Test Before Long Range: A Conservative Checklist',
    category: 'Flight Guides',
    audience: 'intermediate',
    searchIntent: 'informational',
    primaryKeyword: 'FPV range test checklist',
    secondaryKeywords: ['long range FPV test', 'ELRS range test', 'FPV video range test'],
    focus: 'testing range progressively before serious distance',
    outline: ['Define abort limits', 'Radio link test', 'Video link test', 'GPS and failsafe readiness', 'Log and review'],
  },
  {
    slug: 'fpv-race-line-practice-drills',
    title: 'FPV Race Line Practice Drills for Beginners',
    category: 'Racing',
    audience: 'beginner',
    searchIntent: 'informational',
    primaryKeyword: 'FPV race line drills',
    secondaryKeywords: ['drone racing practice', 'FPV racing drills', 'race line FPV'],
    focus: 'learning cleaner race lines before chasing speed',
    outline: ['Why line beats throttle', 'Gate entry and exit', 'Split-S and hairpin drills', 'Consistency tracking', 'When to add speed'],
  },
  {
    slug: 'fpv-maintenance-schedule-for-beginners',
    title: 'FPV Maintenance Schedule for Beginners',
    category: 'Build Guides',
    audience: 'beginner',
    searchIntent: 'informational',
    primaryKeyword: 'FPV maintenance schedule',
    secondaryKeywords: ['FPV drone maintenance', 'drone maintenance checklist', 'FPV motor maintenance'],
    focus: 'keeping a drone reliable through simple scheduled checks',
    outline: ['After every flight day', 'Weekly checks', 'Battery maintenance', 'Motor and frame inspection', 'When to replace parts'],
  },
  {
    slug: 'fpv-prop-wash-troubleshooting-guide',
    title: 'FPV Prop Wash Troubleshooting Guide',
    category: 'Troubleshooting',
    audience: 'intermediate',
    searchIntent: 'diagnostic',
    primaryKeyword: 'FPV prop wash troubleshooting',
    secondaryKeywords: ['Betaflight prop wash', 'FPV tuning guide', 'drone oscillation turns'],
    focus: 'diagnosing prop wash through build, props, and tune evidence',
    outline: ['What prop wash looks like', 'Mechanical causes first', 'Prop selection', 'Filter and PID considerations', 'Retest workflow'],
  },
  {
    slug: 'fpv-cinematic-line-planning-guide',
    title: 'FPV Cinematic Line Planning Guide',
    category: 'Flight Guides',
    audience: 'intermediate',
    searchIntent: 'informational',
    primaryKeyword: 'FPV cinematic line planning',
    secondaryKeywords: ['cinematic FPV planning', 'FPV filming line', 'drone shot planning'],
    focus: 'planning cinematic flight lines before takeoff',
    outline: ['Subject and story', 'Entry and exit', 'Altitude and speed', 'Spotter coordination', 'Review and iterate'],
  },
  {
    slug: 'fpv-beginner-upgrade-path',
    title: 'FPV Beginner Upgrade Path: What to Improve First',
    category: 'News and Reviews',
    audience: 'beginner',
    searchIntent: 'commercial',
    primaryKeyword: 'FPV beginner upgrade path',
    secondaryKeywords: ['FPV upgrades beginner', 'what to upgrade first FPV', 'FPV gear path'],
    focus: 'prioritizing upgrades by skill bottleneck rather than hype',
    outline: ['Identify the real bottleneck', 'Radio and simulator time', 'Goggles and video path', 'Batteries and charger', 'When a new drone makes sense'],
  },
] satisfies readonly EvergreenSeed[];

const evergreenExpansionPlan = evergreenExpansionSeeds.map(buildEvergreenBrief);

export const firstWaveContentPlan = [
  ...coreContentPlan,
  ...evergreenExpansionPlan,
] as const satisfies readonly ContentBrief[];

export const firstWaveContentBySlug = Object.fromEntries(
  firstWaveContentPlan.map((item) => [item.slug, item]),
) as Record<string, (typeof firstWaveContentPlan)[number]>;

export function getFirstWaveContentByCategory(category: ContentCategory) {
  return firstWaveContentPlan.filter((item) => item.category === category);
}

export function getPillarContent() {
  return firstWaveContentPlan.filter((item) => item.tier === 'pillar');
}

export function getSupportingContent() {
  return firstWaveContentPlan.filter((item) => item.tier === 'support');
}
