import React from 'react';
import { CyberBreadcrumb } from '@/features/navigation/components/Breadcrumb';
import { AdStickySidebar } from '@/features/monetization/components/NativeAds';
import { AISummaryBox } from '@/components/ui/AISummaryBox';
import { BookOpen, Cpu, Shield } from 'lucide-react';

export const metadata = {
  title: 'FPV Glossary & Terminology | FPV LOVERS ACADEMY',
  description: 'Field dictionary explaining complex UAV physics, electronics, and standard FPV abbreviations.',
};

const glossaryData = [
  { term: "ELRS (ExpressLRS)", def: "Open-source radio control link offering unparalleled range, low latency, and high refresh rates using LoRa hardware." },
  { term: "VTX (Video Transmitter)", def: "The module responsible for converting the camera feed into RF waves and transmitting it to your goggles." },
  { term: "UART", def: "Universal Asynchronous Receiver-Transmitter. Hardware serial ports on a Flight Controller used to connect peripherals like GPS, Receivers, and Digital VTX." },
  { term: "PID Tuning", def: "Proportional, Integral, Derivative. A control loop feedback algorithm. Tuning PIDs determines how locked-in and snappy the drone feels versus smooth and flowy." },
  { term: "ESC (Electronic Speed Controller)", def: "Translates signals from the Flight Controller into 3-phase alternating current to spin brushless motors at specific RPMs." }
];

export default function GlossaryPage() {
  const breadcrumbs = [
    { label: 'Pilot Academy', href: '/academy' },
    { label: 'FPV Glossary', isCurrentPage: true }
  ];

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 pt-28">
      <CyberBreadcrumb items={breadcrumbs} className="mb-8" />

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
        <div className="lg:col-span-8 flex flex-col gap-10">

          <div className="relative p-8 hex-panel glass-panel overflow-hidden">
             <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/black-scales.png')] opacity-[0.03] mix-blend-overlay" />
             <BookOpen className="w-12 h-12 text-[#00F2FF] mb-6 opacity-80" />
             <h1 className="text-4xl md:text-5xl font-black uppercase text-white tracking-tighter mb-4">
               Tactical <span className="text-[#00F2FF]">Glossary</span>
             </h1>
             <p className="text-sm font-mono text-[#A0A0A0] max-w-2xl leading-relaxed uppercase tracking-widest">
{"// Decrypting aerodynamic telemetry and electrical acronyms generated by the FPV collective."}
</p>
          </div>

          <AISummaryBox
            content="The FPV ecosystem is highly reliant on technical jargon. New pilots must understand the difference between control links (e.g., ELRS, Crossfire) and video links (analog, DJI O3, Walksnail HD) before assembling a custom quadrant."
            title="SYS.LINGUISTIC_ANALYSIS"
          />

          <div className="space-y-4">
             <div className="flex items-center gap-2 border-b border-[#333333] pb-2 mb-6">
                <Cpu className="w-5 h-5 text-[#00A8B3]" />
                <h3 className="text-lg font-black uppercase text-[#f8fafc] tracking-widest">Classified Terms</h3>
             </div>

             <div className="grid gap-4">
                {glossaryData.map((item, i) => (
                   <div key={i} className="bg-black/50 p-6 border border-[#1A1A1A] border-l-2 border-l-[#00F2FF] hex-panel group hover:bg-[#0A0A0B] transition-colors relative">
                      <div className="absolute right-4 top-4 opacity-10 group-hover:opacity-100 transition-opacity">
                         <Shield className="w-6 h-6 text-[#00F2FF]" />
                      </div>
                      <h4 className="text-xl font-black uppercase tracking-tight text-white mb-2 group-hover:text-[#00F2FF] transition-colors">{item.term}</h4>
                      <p className="font-mono text-sm text-[#A0A0A0] leading-relaxed max-w-[90%]">
                        {item.def}
                      </p>
                   </div>
                ))}
             </div>
          </div>

        </div>

        <aside className="lg:col-span-4 hidden lg:flex flex-col gap-6">
           <AdStickySidebar />
        </aside>
      </div>
    </div>
  );
}
